export const LAY_DANH_SACH_BANNER = "LAY_DANH_SACH_BANNER";
export const LAY_DANH_SACH_BANNER_API = 'LAY_DANH_SACH_BANNER_API'
export const LAY_DANH_SACH_PHIM_API = 'LAY_DANH_SACH_PHIM_API'
export const LAY_DANH_SACH_PHIM = 'LAY_DANH_SACH_PHIM'
export const THEM_PHIM_API = 'THEM_PHIM_API'
export const CAP_NHAT_API = 'CAP_NHAT_API'